apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-model-deployment
  labels:
    app: local-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-model
  template:
    metadata:
      labels:
        app: local-model
    spec:
      containers:
        - name: local-model
          image: ling-mlops-sandbox:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
