apiVersion: v1
kind: Service
metadata:
  name: local-model-service
  labels:
    app: local-model
spec:
  type: ClusterIP
  selector:
    app: local-model
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
